### ISSUE TITLE
Allow customization of the instance title

### ISSUE THREAD

**Issue by Kio-td** [ihateblueb/ask-js#14]
Currently, the instance uses the host. It would be really nice if we could configure the name of the instance in the config, or in the admin settings.

**Comment by ihateblueb** [comment]
i had a thing initially that would allow setting it on the meta endpoint, but i had removed it because there was a delay on the page loading. i’ll look into a decent way to do this

**Comment by Kio-td** [comment]
Currently, our workaround is:
```css
header a.subtle {
    visibility: hidden;
}
 
header a.subtle:before {
    visibility: visible;
    content: 'Ask HMS!';
}
```
in the custom.css file.
